import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const skillDir = resolve(__dirname, "..");
const refsDir = resolve(skillDir, "references");
const upstreamManifestPath = resolve(refsDir, "upstream", "manifest.json");

await mkdir(refsDir, { recursive: true });

const upstreamManifest = JSON.parse(await readFile(upstreamManifestPath, "utf8"));
const sourcesBySlug = new Map((upstreamManifest.items || []).map((item) => [item.slug, item]));

const docs = [
    {
        filename: "processing-3d-basics.md",
        title: "Processing 3D Basics",
        body: [
            "Use this when the source material is a Processing sketch that relies on `P3D`, transforms, or point-cloud geometry.",
            "",
            "## Core rules",
            "",
            "- Processing enables 3D rendering by passing `P3D` to `size(width, height, P3D)`.",
            "- Transform calls such as `translate()`, `rotateX()`, `rotateY()`, and `rotateZ()` are cumulative for the current frame.",
            "- `pushMatrix()` and `popMatrix()` scope transform changes and should be preserved during ports.",
            "- `beginShape(POINTS)` plus `vertex(x, y, z)` is the closest Processing-side match for a point-cloud renderer.",
            "- `beginShape()` blocks do not allow transform calls inside them; apply transforms before entering the block.",
            "",
            "## Porting implications",
            "",
            "- Treat the Processing sketch's world coordinates as scene coordinates, not screen pixels.",
            "- Keep point-cloud generation separate from rendering if the source sketch does expensive computation per point.",
            "- Preserve the original transform order before optimizing anything.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "processing-reference-index",
                "processing-size",
                "processing-translate",
                "processing-pushmatrix",
                "processing-popmatrix",
                "processing-rotatex",
                "processing-rotatey",
                "processing-rotatez",
                "processing-beginshape",
                "processing-vertex",
                "processing-point",
            ]),
        ],
    },
    {
        filename: "p5-webgl-controls.md",
        title: "p5 WEBGL Controls",
        body: [
            "Use this when the target implementation is a browser-based p5 sketch with 3D interaction, full-screen shaders, or live controls.",
            "",
            "## Core rules",
            "",
            "- Create the renderer with `createCanvas(width, height, WEBGL)`.",
            "- Use `orbitControl()` in `draw()` for mouse and touch orbiting instead of adding a third-party camera by default.",
            "- Use `loadShader()` plus `shader()` when the heavy math belongs in the fragment shader, such as a Julia-set render.",
            "- Resize the sketch with `resizeCanvas()` inside a resize handler tied to the actual stage container.",
            "- Use `colorMode(HSB, ...)` when the sketch benefits from quick hue-based control over point-cloud color.",
            "- Use sliders, checkboxes, or selects only for values that the user should actively explore.",
            "",
            "## Control strategy",
            "",
            "- Geometry-affecting inputs should trigger a rebuild path, not mutate state inside the hot draw loop.",
            "- Pure render controls such as palette, point size, or autorotation may update immediately without recomputing geometry.",
            "- On mobile, default to lower geometric detail and hide dense controls behind a drawer or sheet.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "p5-createcanvas",
                "p5-loadshader",
                "p5-shader",
                "p5-orbitcontrol",
                "p5-beginshape",
                "p5-vertex",
                "p5-createslider",
                "p5-createcheckbox",
                "p5-createselect",
                "p5-resizecanvas",
                "p5-colormode",
            ]),
        ],
    },
    {
        filename: "processing-to-p5-porting.md",
        title: "Processing to p5 Porting Rules",
        body: [
            "Use this when porting a Processing sketch into `fun/projects/<slug>/`.",
            "",
            "## Default mappings for this repo",
            "",
            "- `size(..., P3D)` -> `createCanvas(..., WEBGL)`",
            "- `pushMatrix()` / `popMatrix()` -> `push()` / `pop()`",
            "- Processing `point()` clouds -> p5 `beginShape(POINTS)` and `vertex(...)` unless individual point styling demands another path",
            "- Processing camera helpers -> p5 `orbitControl()`",
            "- Heavy Processing loops that both compute and draw -> worker-based generation plus a lean `draw()` loop in p5",
            "",
            "## Repo-specific conventions",
            "",
            "- Keep the project local to its own folder under `fun/projects/`.",
            "- Add at most one card to `/fun/`; do not move project-specific logic into global scripts.",
            "- Pin the p5 runtime locally for the project unless the exact same runtime is intentionally shared across multiple fun projects.",
            "- If the port needs long-form notes, put them in the skill references or `writings/`, not inline in the project code.",
            "",
            "## Validation checklist",
            "",
            "- The visual structure matches the source sketch's logic before visual polish starts.",
            "- Orbiting and resize behavior work on both desktop and mobile.",
            "- Expensive state changes do not freeze the UI or leave stale geometry onscreen.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "processing-size",
                "processing-translate",
                "processing-rotate",
                "processing-pushmatrix",
                "processing-popmatrix",
                "processing-line",
                "processing-beginshape",
                "processing-vertex",
                "p5-createcanvas",
                "p5-translate",
                "p5-rotate",
                "p5-push",
                "p5-pop",
                "p5-orbitcontrol",
                "p5-resizecanvas",
            ]),
        ],
    },
    {
        filename: "p5-2d-recursion.md",
        title: "p5 2D Recursion",
        body: [
            "Use this when the target sketch is a recursive 2D drawing, a constrained particle-growth system, or an iterative segment-replacement curve such as a fractal tree, branching plant, Koch-style line system, or Brownian snowflake.",
            "",
            "## Core rules",
            "",
            "- Treat each recursive branch as a transform scope: draw the segment, translate to its end, then recurse inside `push()` / `pop()` blocks.",
            "- Keep the branch function visually pure. It should receive the current segment length and depth, then draw from the local origin.",
            "- `translate()` should move the origin to the branch tip before child branches are drawn.",
            "- `rotate()` should only affect the current branch scope.",
            "- Use `strokeWeight()` decay rather than a fixed line width so the tree reads as a hierarchy instead of a symbol.",
            "- For Koch-like systems, keep subdivision logic separate from drawing logic. First generate the ordered segment or point list, then render it.",
            "",
            "## Interaction guidance",
            "",
            "- Geometry is cheap enough to rebuild every frame for most tree sketches; a worker is unnecessary unless the branch count explodes.",
            "- HTML controls are often clearer than p5 DOM controls when the page already has a site-specific layout shell.",
            "- Use motion sparingly: a small sway or breathing effect is enough to keep the tree alive without obscuring the recursive structure.",
            "- For segment-replacement fractals, rebuild only when structure parameters change. Color, pulse, and rotation can stay in the draw loop.",
            "- For Brownian growth systems, keep the live walker in wedge-local coordinates and apply symmetry only during rendering.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "coding-train-fractal-tree-challenge",
                "coding-train-fractal-tree-p5-source",
                "coding-train-fractal-tree-processing-source",
                "coding-train-koch-snowflake-p5-sketch",
                "coding-train-koch-snowflake-p5-segment",
                "coding-train-koch-snowflake-processing-sketch",
                "coding-train-koch-snowflake-processing-segment",
                "coding-train-brownian-snowflake-challenge",
                "coding-train-brownian-snowflake-p5-sketch",
                "coding-train-brownian-snowflake-p5-particle",
                "coding-train-brownian-snowflake-processing-sketch",
                "coding-train-brownian-snowflake-processing-particle",
                "p5-line",
                "p5-beginshape",
                "p5-endshape",
                "p5-translate",
                "p5-rotate",
                "p5-scale",
                "p5-push",
                "p5-pop",
                "p5-strokeweight",
                "processing-line",
                "processing-beginshape",
                "processing-endshape",
                "processing-translate",
                "processing-rotate",
                "processing-scale",
                "processing-pushmatrix",
                "processing-popmatrix",
            ]),
        ],
    },
    {
        filename: "fractal-tree-notes.md",
        title: "Fractal Tree Notes",
        body: [
            "Use this when implementing or extending the Coding Train Fractal Tree sketch.",
            "",
            "## Reference structure",
            "",
            "- The original challenge is a compact recursive binary tree: draw one trunk segment, translate upward, branch left and right with the same angle, and stop when the current length falls below a threshold.",
            "- The p5 version uses a slider to control the angle in real time.",
            "- The Processing port preserves the same recursive structure and adds mouse-wheel angle control.",
            "",
            "## Safe extensions",
            "",
            "- Add controls for angle, branch ratio, trunk length, and minimum twig length before adding more decorative parameters.",
            "- Motion should perturb the branch angle slightly over time, not replace the underlying recursive structure.",
            "- Leaves or blossoms should only appear near terminal twigs so the tree silhouette remains legible.",
            "- Presets are a good extension point because they let the sketch stay reference-faithful while still being playful.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "coding-train-fractal-tree-challenge",
                "coding-train-fractal-tree-p5-source",
                "coding-train-fractal-tree-processing-source",
            ]),
        ],
    },
    {
        filename: "koch-snowflake-notes.md",
        title: "Koch Snowflake Notes",
        body: [
            "Use this when implementing or extending the Coding Train Koch Snowflake sketch.",
            "",
            "## Reference structure",
            "",
            "- The original challenge starts from an equilateral triangle and replaces each segment with four child segments.",
            "- The p5 source isolates the subdivision math inside a `Segment` class and applies one generation step per mouse press.",
            "- The key operation is: split the segment into thirds, rotate the middle third by `-PI / 3`, and connect the four resulting segments in order.",
            "",
            "## Safe extensions",
            "",
            "- Keep the ordered segment list or point list intact so the snowflake remains drawable as one continuous polyline or polygon.",
            "- Add controls for iteration count, seed polygon sides, radius, and peak angle before introducing more exotic deformation.",
            "- Treat color, pulse, and slow rotation as render-only parameters so geometry is not rebuilt unnecessarily.",
            "- When generalizing beyond the equilateral case, be explicit about the turn direction so spikes keep pointing outward.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "coding-train-koch-snowflake-p5-sketch",
                "coding-train-koch-snowflake-p5-segment",
                "coding-train-koch-snowflake-processing-sketch",
                "coding-train-koch-snowflake-processing-segment",
            ]),
        ],
    },
    {
        filename: "brownian-snowflake-notes.md",
        title: "Brownian Snowflake Notes",
        body: [
            "Use this when implementing or extending the Coding Train Brownian snowflake sketch.",
            "",
            "## Reference structure",
            "",
            "- The original challenge keeps exactly one active walker in a narrow wedge, lets it drift inward with random vertical motion, and sticks it to the cluster once it touches an existing particle or reaches the center.",
            "- The full snowflake is rendered by rotating that wedge six times and mirroring each copy with `scale(1, -1)`.",
            "- The p5 and Processing versions both clamp the walker's heading into the wedge after each step, which is the key reason the crystal grows with clean radial symmetry.",
            "",
            "## Safe extensions",
            "",
            "- Keep the walker simulation and the symmetry rendering as separate concerns. The particle list should stay in wedge-local coordinates.",
            "- Controls for drift, jitter, particle radius, spawn radius, and steps per frame are safe extension points because they preserve the underlying DLA logic.",
            "- Visual changes such as hue, glow, and slow whole-form rotation should stay render-only and must not mutate the stored particle positions.",
            "- If a structural parameter changes, restart the growth. Reusing an old cluster under a different wedge or sticking radius produces misleading results.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "coding-train-brownian-snowflake-challenge",
                "coding-train-brownian-snowflake-p5-sketch",
                "coding-train-brownian-snowflake-p5-particle",
                "coding-train-brownian-snowflake-processing-sketch",
                "coding-train-brownian-snowflake-processing-particle",
                "p5-rotate",
                "p5-scale",
                "processing-rotate",
                "processing-scale",
            ]),
        ],
    },
    {
        filename: "julia-set-notes.md",
        title: "Julia Set Shader Notes",
        body: [
            "Use this when implementing or extending the Julia-set shader reference repo.",
            "",
            "## Reference structure",
            "",
            "- The reference project is deliberately small: one p5 `WEBGL` canvas, one vertex shader, one fragment shader, and a single animated angle that moves the Julia constant `c` along a path.",
            "- The fragment shader owns the escape-time loop. Each pixel maps into the complex plane, iterates `z = z^2 + c`, and colors by escape behavior.",
            "- The original sketch keeps the view window fixed and only animates the parameter path, so the most meaningful browser controls are around parameter drift, zoom, and render detail.",
            "",
            "## Safe extensions",
            "",
            "- Keep the fragment shader responsible for the expensive iteration work. JavaScript should mostly manage uniforms, resize behavior, and interaction.",
            "- A small control set is enough: parameter phase, zoom, iteration count, palette shift, and optional drift speed.",
            "- Prefer pointer drag and wheel zoom for navigation instead of adding sliders for center coordinates.",
            "- If auto-drift exists, let it update the same phase variable that the manual slider controls so the mental model stays simple.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "vharivinay-julia-set-readme",
                "vharivinay-julia-set-sketch",
                "vharivinay-julia-set-frag",
                "vharivinay-julia-set-vert",
                "p5-createcanvas",
                "p5-loadshader",
                "p5-shader",
                "p5-resizecanvas",
            ]),
        ],
    },
    {
        filename: "mandelbulb-notes.md",
        title: "Mandelbulb Notes",
        body: [
            "Use this when implementing or tuning a Mandelbulb point cloud in p5.",
            "",
            "## Baseline approach",
            "",
            "- Stay close to the Coding Train challenge: sample 3D space, run the Mandelbulb escape test in spherical coordinates, and render the retained points as a cloud.",
            "- Default to a surface-shell extraction so the form reads well before a shader or volume renderer exists.",
            "- Keep interaction playful: preview quickly at lower resolution, then refine after input settles.",
            "",
            "## Good default parameters",
            "",
            "- `power`: 8",
            "- `maxIterations`: around 10 to 14",
            "- `bounds`: around 1.1 to 1.3",
            "- `escapeRadius`: 2 to 4 for reference-faithful builds; allow broader experimentation separately",
            "- `gridResolution`: start around 28 to 44 and refine upward only when interaction remains smooth",
            "",
            "## Rendering guidance",
            "",
            "- Keep geometry generation off the main thread.",
            "- Retain the last completed geometry until the replacement dataset is ready.",
            "- Support manual orbiting at all times even if autorotation is enabled.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "coding-train-mandelbulb",
                "processing-beginshape",
                "processing-vertex",
                "p5-beginshape",
                "p5-vertex",
                "p5-orbitcontrol",
            ]),
        ],
    },
    {
        filename: "performance-checklist.md",
        title: "Creative Coding Performance Checklist",
        body: [
            "Use this when a p5 or Processing-style sketch risks becoming computation-bound in the browser.",
            "",
            "## Checklist",
            "",
            "- Separate geometry generation from rendering.",
            "- Use a worker for heavy point-cloud or voxel generation.",
            "- Cancel stale rebuilds instead of queueing multiple expensive jobs.",
            "- Keep `draw()` deterministic and lean.",
            "- Lower default resolution on small screens.",
            "- Avoid mutating the current visible geometry until the new dataset is complete.",
            "- Prefer native HTML controls or a small control surface over rebuilding large p5 DOM hierarchies.",
            "- Use `pixelDensity(1)` unless a specific visual requirement needs more.",
            "",
            "## Realtime interaction model",
            "",
            "- First render a coarse preview.",
            "- After the last input event settles, compute the refined geometry.",
            "- Render-only settings should update immediately without forcing a rebuild.",
            "",
            "## Relevant upstream snapshots",
            "",
            sourceList([
                "p5-createcanvas",
                "p5-resizecanvas",
                "p5-orbitcontrol",
                "coding-train-mandelbulb",
            ]),
        ],
    },
];

for (const doc of docs) {
    const target = resolve(refsDir, doc.filename);
    await writeFile(target, renderDocument(doc.title, doc.body), "utf8");
}

console.log(`Built ${docs.length} curated reference files.`);

function renderDocument(title, lines) {
    return `# ${title}

${lines.join("\n")}
`;
}

function sourceList(slugs) {
    return slugs
        .map((slug) => {
            const source = sourcesBySlug.get(slug);
            if (!source) {
                return `- ${slug} (missing from upstream manifest)`;
            }

            const freshness = source.fetchedAt ? `, fetched ${source.fetchedAt}` : "";
            return `- ${source.label}: ${source.finalUrl || source.url}${freshness}`;
        })
        .join("\n");
}
